### ISSUE TITLE
Add `covr` to Travis script

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/cirtwo#5]
* Difficulty: 1/10

To the `.travis.yml` script, add:

```
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e "covr::codecov()"
```

**Comment by richelbilderbeek** [comment]
Moving to 'Done' is insufficient to close the Issue.

Please close the Issue with a message, e.g. 'Done!' and click 'Close and comment' :+1:

**Comment by TheoPannetier** [comment]
done
